const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')

const manifest = JSON.parse(fs.readFileSync('manifest.json', 'utf8'))
const contract = JSON.parse(fs.readFileSync('contract.json', 'utf8'))
const controllerVersion = fs.readFileSync('upstream-version.txt', 'utf8').trim()
const readme = fs.readFileSync('README.md', 'utf8')
const panel = fs.readFileSync('Panel.qml', 'utf8')
const model = require('../Model.js')
const schemaPatch = fs.readFileSync('patches/status-schema-v1.patch', 'utf8')

test('plugin and controller compatibility versions stay explicit and aligned', () => {
  assert.match(manifest.version, /^\d+\.\d+\.\d+$/)
  assert.match(controllerVersion, /^\d+\.\d+\.\d+$/)
  assert.equal(contract.controllerVersion, controllerVersion)
  assert.equal(contract.schemaVersion, model.STATUS_SCHEMA_VERSION)
  assert.deepEqual(contract.capabilities, model.STATUS_CAPABILITIES)
  assert.equal(manifest.version.split('.').slice(0, 2).join('.'), controllerVersion.split('.').slice(0, 2).join('.'))
  assert.match(readme, new RegExp(`@stateset/cli@${controllerVersion.replaceAll('.', '\\.')}`))
  assert.match(panel, new RegExp(`@stateset/cli@${controllerVersion.replaceAll('.', '\\.')}`))
  assert.equal(model.CONTROLLER_SERIES, controllerVersion.split('.').slice(0, 2).join('.'))
  assert.match(schemaPatch, /controllerVersion: CLI_VERSION/)
  assert.match(schemaPatch, /schemaVersion: OMARCHY_CONTRACT\.schemaVersion/)
  assert.match(schemaPatch, /capabilities: \[\.\.\.OMARCHY_CAPABILITIES\]/)
  assert.match(schemaPatch, /\.\.\.OMARCHY_CONTRACT\.capabilities/)
})

test('release tags are created only after protected-master validation', () => {
  const workflow = fs.readFileSync('.github/workflows/tag-release.yml', 'utf8')
  assert.match(workflow, /workflow_run:/)
  assert.match(workflow, /conclusion == 'success'/)
  assert.match(workflow, /head_branch == 'master'/)
  assert.match(workflow, /Validated commit is not a release commit; nothing to tag/)
  assert.match(workflow, /Tag v\$version already points to the validated release/)
  assert.match(workflow, /refusing to move it/)
  assert.match(workflow, /git push origin "refs\/tags\/v\$version"/)
  assert.doesNotMatch(workflow, /--force/)
})
